### ISSUE TITLE
Is this project alive? 

### ISSUE THREAD

**Issue by mrhitman** [aws/aws-greengrass-core-sdk-js#23]
Seems like its official package for AWS Greengrass v2, but it's last updated 3 years ago. Examples outdated a guess. Should I use it, or there some more valid package for greengrass?

**Comment by MikeDombo** [comment]
This is for Greengrass V1. Greengrass V1 is in maintenance mode and will not receive updates after July 2023.

For Greengrass V2, please see https://docs.aws.amazon.com/greengrass/v2/developerguide/interprocess-communication.html for information about using IPC in Greengrass V2.
