### ISSUE TITLE
Support for StreamManager

### ISSUE THREAD

**Issue by HQarroum** [aws/aws-greengrass-core-sdk-js#3]
The Greengrass SDK for Javascript does not support the new [StreamManager](https://docs.aws.amazon.com/greengrass/latest/developerguide/stream-manager.html) feature of AWS Greengrass 1.10, where the SDKs for Java and Python does support StreamManager.

**Comment by MikeDombo** [comment]
Support is now included in version 1.6.0 of the SDK: https://github.com/aws/aws-greengrass-core-sdk-js/releases/tag/v1.6.0.

Thanks for the suggestion.
