### ISSUE TITLE
callback(null, data); error

### ISSUE THREAD

**Issue by mariopereiragit** [aws/aws-greengrass-core-sdk-js#4]
[2019-12-05T17:47:39.524Z][ERROR]-/lambda/node_modules/aws-greengrass-core-sdk/iotdata.js:136
[2019-12-05T17:47:39.524Z][ERROR]-                callback(null, data);           // successful response
[2019-12-05T17:47:39.524Z][ERROR]-                ^
[2019-12-05T17:47:39.524Z][ERROR]-TypeError: callback is not a function
[2019-12-05T17:47:39.524Z][ERROR]-    at lambda.invoke (/lambda/node_modules/aws-greengrass-core-sdk/iotdata.js:136:17)
[2019-12-05T17:47:39.524Z][ERROR]-    at ipc.postWork (/lambda/node_modules/aws-greengrass-core-sdk/lambda.js:110:17)
[2019-12-05T17:47:39.524Z][ERROR]-    at IncomingMessage.res.on (/runtime/nodejs/node_modules/aws-greengrass-ipc-sdk-js/ipcclient.js:108:33)
[2019-12-05T17:47:39.524Z][ERROR]-    at emitNone (events.js:111:20)
[2019-12-05T17:47:39.524Z][ERROR]-    at IncomingMessage.emit (events.js:208:7)
[2019-12-05T17:47:39.524Z][ERROR]-    at endReadableNT (_stream_readable.js:1064:12)
[2019-12-05T17:47:39.524Z][ERROR]-    at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2019-12-05T17:47:39.524Z][ERROR]-    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by MikeDombo** [comment]
What is the code you're running which is calling the `invoke`?

**Comment by mariopereiragit** [comment]
const opcua = require("node-opcua");
const IotData = require('aws-greengrass-core-sdk').IotData;
const opcauth = require('./auth')

const opcuaserver = process.env.opcuaserver;

const device = new IotData();

const client = opcua.OPCUAClient.create({
  endpoint_must_exist: false,
  reconnectOnFailure: true,
  keepSessionAlive: true,
  keepPendingSessionsOnDisconnect: true,
});

const endpointUrl = opcuaserver;

let the_session, the_subscription;

client.on("backoff", function (retry, delay) {
  console.log("still trying to connect to ", endpointUrl, ": retry =", retry, "next attempt in ", delay / 1000, "seconds");
});
client.on('connection_lost', function () {
  console.log('Connection lost');
});
client.on('connected', function () {
  console.log('connected');
});
client.on('connection_failed', function () {
  console.log('connection failed');
});
client.on('abort', function () {
  console.log('connection abort');
});

createOPCConnection()
  .then(function () {
    createOPCSession()
      .then(function (response) {
        the_session = response;
        createOPCSubscription()
          .then(function () {
            monitorItems();
          })
      })
      .catch(function (response) {
        console.log(response);
      })
  })
  .catch(function (response) {
    console.log(response)
  })

function createOPCConnection() {
  return new Promise(function (resolve, reject) {
    client.connect(endpointUrl, function (err) {
      if (!err) {
        console.log('succesfully connected');
        resolve('Succesfully connected');
      } else {
        console.log('Error connecting : ', err);
        reject('Error connecting : ', err);
      }
    })
  })
}

function createOPCSession() {
  return new Promise(function (resolve, reject) {
    client.createSession(opcauth, function (err, session) {
      if (!err) {
        console.log('session created');
        console.log(session.sessionId);

        session.on('session_closed', function (status) {
          sessionIsClosed = true;
          console.log('session closed : ', status)
        });
        resolve(session);
      } else {
        console.log('error creating session : ', err);
        reject('error creating session : ', err);
      }
    })
  })
}

function createOPCSubscription() {
  const options = {
    requestedPublishingInterval: 1000,
    requestedLifetimeCount: 2000,
    requestedMaxKeepAliveCount: 10,
    maxNotificationsPerPublish: 1000,
    publishingEnabled: true
  };

  return new Promise(function (resolve) {
    the_subscription = opcua.ClientSubscription.create(the_session, options);
    the_subscription.on('started', function () {
      console.log('subscription started');
    });
    the_subscription.on('terminated', function () {
      console.log('subscription terminated');
    });
    the_subscription.on('keepalive', function () {
      console.log('subscription keepalive');
    });
    the_subscription.on('internal_error', function (err) {
      console.log('subscription internal error : ', err);
    });
    the_subscription.on('status_changed', function (statuscode) {
      console.log('subscription status changed : ', statuscode);
    });
    the_subscription.on('error', function (err) {
      console.log('subscription error : ', err);
    });
    resolve(the_subscription);
  })

}

function monitorItems() {
  console.log("Monitoring starting")
  const itemsToMonitor = [
    {
      nodeId: opcua.resolveNodeId("ns=2;s=SGPSimulator.WB-356-66.mass"),
      attributeId: opcua.AttributeIds.Value
    }
  ];
  const requestedParameters = {
    samplingInterval: 100,
    discardOldest: true,
    queueSize: 100
  };
  the_subscription.monitorItems(itemsToMonitor, requestedParameters, opcua.TimestampsToReturn.Both).then(function (monitoredItems) {
    console.log("Subscription monitoring items started ");
    monitoredItems.on("changed", function (item, dataValue, index) {
      console.log(dataValue.value.value);
      const opcpayload = dataValue.value.value;
        const topic = `opcua/`.toLowerCase();
        const payloadStr = JSON.stringify(opcpayload);
        device.publish(
          {
            topic: topic,
            payload: payloadStr
          })
    });
  });
}

**Comment by MikeDombo** [comment]
your line at the end: `device.publish(...)` needs a callback function. Even if you don't want to do anything with the callback, you need to define some function. You can even just have a do-nothing callback `() => {}`.

**Comment by mariopereiragit** [comment]
ah ok, thx!
