### ISSUE TITLE
Error during function's handler invoke

### ISSUE THREAD

**Issue by daaru00** [aws/aws-greengrass-core-sdk-js#5]
Hello,

I have an error during Lambda (NodeJS 12.x) execution: 
```
Error: Failed to invoke handler: TypeError: Cannot read property 'apply' of undefined
    at Invocation.invoke (/runtime/nodejs/lambda_nodejs_runtime.js:173:25)
    at Runtime.doInvoke (/runtime/nodejs/lambda_nodejs_runtime.js:318:39)
    at wrappedTaskToTryCallback (/runtime/nodejs/node_modules/aws-greengrass-common-js/retry.js:55:39)
    at IncomingMessage.<anonymous> (/runtime/nodejs/node_modules/aws-greengrass-ipc-sdk-js/ipcclient.js:67:33)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
error coming from `/greengrass/ggc/core/runtime/nodejs/lambda_nodejs_runtime.js` and not from my code, don't know if related to this repository or not.

**Comment by MikeDombo** [comment]
This error has to do with the GG lambda runtime being unable to invoke your lambda function handler. 
What do you have the lambda function handler set to in your lambda settings, and how is it implemented in the code?

**Comment by daaru00** [comment]
>What do you have the lambda function handler set to in your lambda settings

executing Lambda in cloud (from Lambda AWS console test tool) is correctly invoked and I'm using the same entrypoint.

> and how is it implemented in the code?

an ES6 handler function exported via `exports`:
```js
/**
 * Lambda handler
 */
exports.handler = async (event) =>  {
  console.log('Event received: ' + JSON.stringify(event))
  // .. 
}
```

**Comment by MikeDombo** [comment]
Unfortunately your handler cannot be an async function. Please see https://github.com/aws/aws-greengrass-core-sdk-js/blob/master/greengrassExamples/HelloWorld/index.js#L40 for an example handler.

**Comment by daaru00** [comment]
Are you saying that Greengrass runtime cannot handle Promise/Async handlers? 

I'm little bit surprise, Lambda support it since v8.10 (2018).. it's almost natural in NodeJS and Lambda environment to use async/await..

**Comment by MikeDombo** [comment]
You can use async/await in any place except for the main function handler. Right now that must be a regular function.
